### ISSUE TITLE
Is this still under development ?

### ISSUE THREAD

**Issue by lvndry** [SilentCicero/react-dapp-boilerplate#4]
# React Boilerplate

I'd like to know if this project is this in development as the last commit as a year ago and if this can be used in production?

**Comment by SilentCicero** [comment]
I wouldn't recommend it. I no longer maintain it. It is for educational purposes ATM. I switched to react / webpack and never looked back. Best of luck!

**Comment by lvndry** [comment]
Sad it was a really good project! Thank you!
